config/routes.rb
Rails.application.routes.draw do

  root 'magazines#index'

  resources :articles

  resources :magazines

  resources :comments do
    member do
      post :create_child
      delete :destroy
    end  
  end

  match "/auth/:provider/callback", to: "sessions#create", via: [:get,:post]
  match "/auth/failure", to: "sessions#failure", via: [:get]

  get '/home' => 'sessions#new', as: :login

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :magazine
	belongs_to :author, class_name: 'User', foreign_key: 'author_id'
	has_many :comments, :as => :commentable

	acts_as_commentable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/models/magazine.rb
class Magazine < ActiveRecord::Base
	has_many :articles
end

app/models/user.rb
class User < OmniAuth::Identity::Models::ActiveRecord
	has_many :articles, foreign_key: 'author_id'
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  before_filter :require_user

  def require_user
  	unless current_user
  		redirect_to login_path
  	end	
  end	
  
  private
  def current_user
    @current_user ||= User.find_by_email(session[:user_email]) if session[:user_email]
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new
		@comment = Comment.new
	end	

	def create
		# debugger
		@article = Article.where(id: params[:article_id]).first
		@comment = Comment.build_from( @article, current_user.id, params[:comment] )
		@comment.save
		redirect_to @article, notice: "Comment added!"
		puts "hi"
	end	

	def create_child
		parent_comment = Comment.where(id: params[:id]).first
		article = parent_comment.commentable
		@comment = Comment.build_from( article, current_user.id, params[:comment] )
		@comment.save
		@comment.move_to_child_of(parent_comment)		
		redirect_to article, notice: "Comment added!"
	end	

	def destroy
		comment = Comment.where(id: params[:id]).first
		comment.destroy
		redirect_to comment.commentable, notice: 'Comment deleted!'
	end	
end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController

  def index
    @magazines = Magazine.includes( articles: [:comments]).all
  end

  def show
    @magazine = Magazine.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_filter :require_user

  def new
  end	

  def create
    # raise request.env["omniauth.auth"].to_yaml
    auth_hash = request.env['omniauth.auth']
	session[:user_email] = auth_hash['info']['email']
    redirect_to root_path, notice: 'Logged in'
  end

  def failure  	
    redirect_to login_path
  end  

  def destroy  	
  	session[:user_email] = nil if current_user
  end	

  	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_child_comments.html.slim
/h6 child partial
- if comment.children.present?
	  - comment.children.each do |child_comment|
	  		.row			  
			  .col-md-offset-1.col-md-2
			  	= child_comment.user.name
			  .col-md-6
				= child_comment.body
				= child_comment.id
			  .col-md-2
		  		= link_to "Comments #{child_comment.children.count}","#child_comments_#{child_comment.id}", data: {toggle: 'collapse'}
			  - if child_comment.children.blank? && comment.user == current_user
				  .col-md-1
				  	= link_to comment_path(child_comment), method: 'delete' do
				  	  |Delete
		  	.row.collapse id="child_comments_#{child_comment.id}"
		  		.col-md-offset-2
		  			= render partial: 'child_comments', locals: {comment: child_comment}	

br
.row
	= form_tag create_child_comment_path(comment.id) do
	  .col-md-offset-2.col-md-6
		= text_area_tag :comment, nil, placeholder: 'Comment here', rows: 2, cols: 10, class: 'col-md-12'
	  .col-md-2		
		= submit_tag 'Add'
br

app/views/articles/index.html.slim
h1 Listing articles

table
  thead
    tr
      th Name
      th Description
      th Magazine
      th
      th
      th

  tbody
    - @articles.each do |article|
      tr
        td = article.name
        td = article.description
        td = article.magazine_id
        td = link_to 'Show', article

br

= link_to 'New Article', new_article_path

app/views/articles/show.html.slim
p#notice = notice

p
  strong Title:
  = @article.title
p
  strong Body:
  = @article.body
p
  strong Magazine:
  = @article.magazine.name

p 
 b Comments #{@article.root_comments.count}

- @article.root_comments.each do |comment|
	.row
	  .col-md-2
	  	= comment.user.name
	  .col-md-6
		= comment.body
	  .col-md-2
	  	= link_to "Comments #{comment.children.count}","#child_comments_#{comment.id}", data: {toggle: 'collapse'}
	  - if comment.children.blank? && comment.user == current_user
		  .col-md-2
		  	= link_to comment_path(comment), method: 'delete' do
		  	  |Delete
	.row.collapse id="child_comments_#{comment.id}"
	  .col-md-offset-2	  	
		= render partial: 'child_comments', locals: {comment: comment}
	
/= link_to 'Add Comment', new_comment_path, remote: true

.row
	= form_tag comments_path(article_id: @article.id) do
		= text_area_tag :comment, nil, placeholder: 'Comment here', rows: 2, cols: 10, class: 'col-md-12'
		br
		br
		br
		= submit_tag 'Comment'


br
br
br
= link_to 'Edit', edit_article_path(@article)
'|
= link_to 'Back', articles_path

app/views/comments/new.js.erb
$("#all_comments").html("<%= render partial: '' %>")

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "MagazineApp"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"



  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="/"MagazineApp
          = link_to 'Log out',"#", class: 'pull-right'
          /.navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield
        /.col-lg-3
          .well.sidebar-nav
            h3 Sidebar
            ul.nav.nav-list
              li.nav-header Sidebar
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

      footer
        p &copy; Company 2015

app/views/magazines/index.html.slim
h1 Listing magazines

table.table
  thead
    tr
      th Name
      th Description
      th Articles
      th Comments(Top Level)
      th

  tbody
    - @magazines.each do |magazine|
      tr
        td = magazine.name
        td = magazine.description        
        td = magazine.articles.count
        td = magazine.articles.map(&:root_comments).flatten.count
        td = link_to 'Show', magazine
br

= link_to 'New Magazine', new_magazine_path

app/views/magazines/show.html.slim
p#notice = notice

p
  strong Name:
  = @magazine.name
p
  strong Description:
  = @magazine.description

= link_to 'Edit', edit_magazine_path(@magazine)
'|
= link_to 'Back', magazines_path

br

h4 Articles

table.table
  thead
    tr
      th Title
      th Body
      /th Magazine
      th

  tbody

	- @magazine.articles.each do |article|
	      tr
	        td = article.title
	        td = article.body
	        /td = article.magazine_id
	        td = link_to 'Show', article